 
 /*------------------------------------------------------------------------
    File        : businesstask
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : boosterm
    Created     : Tue Apr 26 12:41:51 CEST 2011
    Notes       : 
  ----------------------------------------------------------------------*/

using bfv.oera.base.BusinessComponent.

routine-level on error undo, throw.

class bfv.oera.base.businesstask inherits BusinessComponent: 
  
end class.
