/*------------------------------------------------------------------------
    File        : icomponent
    Purpose     : 
    Syntax      : 
    Description : Interface definition of an application component
    Author(s)   : 
    Created     : 
    Notes       : 
  ----------------------------------------------------------------------*/
  
interface bfv.oera.interfaces.IComponent: 
  
  method public void InitializeComponent().
  method public void DestroyComponent().
     
end interface.
