/*------------------------------------------------------------------------
    File        : icomponent
    Purpose     : 
    Syntax      : 
    Description : Interface definition of an application component
    Author(s)   : 
    Created     : 
    Notes       : 
  ----------------------------------------------------------------------*/
  
  INTERFACE bfv.oera.interfaces.icomponent: 
      METHOD PUBLIC VOID initializeComponent().
      METHOD PUBLIC VOID destroyComponent().
      
  END INTERFACE.
