
interface bfv.lib.system.ISingleton:  

  /* lege interface, een class die deze interface implementeert wordt als 
     singleton behandeld door ObjectFactory. Er zijn twee gevallen:
   * - het heeft de voorkeur dat een class als singleton wordt gebruikt
   * - het is noodzakelijk dat een class als singleton wordt gebruikt
   * 
   * In het tweede geval moet de class zelf voorzien in het gewenste gedrag
   */  
     
end interface.